name: 'Gitbook Action Build'
on:
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Get Branch
      run: |
        branch=${{ github.ref_name }}
        pubdir=${branch/master/draft}
        pubdir=${pubdir////-}
        echo "ON_PUSH_BRANCH_NAME=$branch" >> $GITHUB_ENV
        echo "ON_PUSH_PUBDIR=$pubdir" >> $GITHUB_ENV
    - name: Gitbook Action
      uses: zanderzhao/gitbook-action@v1.2.4
      with:
        token: ${{secrets.GITBOOK_ACTION_PERSONAL_TOKEN}}
        source_branch: ${{env.ON_PUSH_BRANCH_NAME}}
        publish_branch: gh-pages
        publish_dir: ${{env.ON_PUSH_PUBDIR}}
        publish_remove_last_build: true
        gitbook_pdf: true
        gitbook_pdf_dir: /
        gitbook_pdf_name: ${{ github.event.repository.name }}-${{env.ON_PUSH_PUBDIR}}
        gitbook_epub: true
        gitbook_epub_dir: /
        gitbook_epub_name: ${{ github.event.repository.name }}-${{env.ON_PUSH_PUBDIR}}
        gitbook_mobi: true
        gitbook_mobi_dir: /
        gitbook_mobi_name: ${{ github.event.repository.name }}-${{env.ON_PUSH_PUBDIR}}
