name: 'Gitbook Action Build'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - main
      - release/*
  workflow_dispatch:

jobs:
  publish-gitbook-docs:
    name: Publish GitBook Docs
    runs-on: ubuntu-latest
    steps:
      - name: Publish GitBook Docs
        uses: tianocore-docs/publish-gitbook-docs@main
        with:
          token: ${{secrets.GITBOOK_ACTION_PERSONAL_TOKEN}}
